import '../declarations/spinal-core-connectorjs';
declare module "spinal-core-connectorjs_types" {
  import * as spinalCore from 'spinal-core-connectorjs';
  const Model: typeof spinal.Model;
  const Str: typeof spinal.Str;
  const Bool: typeof spinal.Bool;
  const Val: typeof spinal.Val;
  const Lst: typeof spinal.Lst;
  const Directory: typeof spinal.Directory;
  const Vec: typeof spinal.Vec;
  const Path: typeof spinal.Path;
  const File: typeof spinal.File;
  const Ptr: typeof spinal.Ptr;
  const Choice: typeof spinal.Choice;
  const TypedArray: typeof spinal.TypedArray;
  const TypedArray_Int32: typeof spinal.TypedArray_Int32;
  const TypedArray_Float32: typeof spinal.TypedArray_Float32;
  const TypedArray_Float64: typeof spinal.TypedArray_Float64;
  const Process: typeof spinal.Process;
  const BindProcess: typeof spinal.BindProcess;
  const FileSystem: typeof spinal.FileSystem;
  export default spinalCore;
  export { spinalCore };
  export { Model };
  export { Str };
  export { Bool };
  export { Val };
  export { Lst };
  export { Directory };
  export { Vec };
  export { Path };
  export { File };
  export { Ptr };
  export { Choice };
  export { TypedArray };
  export { TypedArray_Int32 };
  export { TypedArray_Float32 };
  export { TypedArray_Float64 };
  export { Process };
  export { BindProcess };
  export { FileSystem };
}

