export * from 'spinal-core-connectorjs';
import * as spinalCore from 'spinal-core-connectorjs';
export default spinalCore;
import { Model as _Model, Str as _Str, Bool as _Bool, Val as _Val, Lst as _Lst, Directory as _Directory, Vec as _Vec, Path as _Path, File as _File, Ptr as _Ptr, Choice as _Choice, TypedArray as _TypedArray, TypedArray_Int32 as _TypedArray_Int32, TypedArray_Float64 as _TypedArray_Float64, Process as _Process, BindProcess as _BindProcess, FileSystem as _FileSystem, Pbr as _Pbr } from 'spinal-core-connectorjs';
declare const Model: typeof _Model;
declare const Str: typeof _Str;
declare const Bool: typeof _Bool;
declare const Val: typeof _Val;
declare const Lst: typeof _Lst;
declare const Directory: typeof _Directory;
declare const Vec: typeof _Vec;
declare const Path: typeof _Path;
declare const File: typeof _File;
declare const Ptr: typeof _Ptr;
declare const Pbr: typeof _Pbr;
declare const Choice: typeof _Choice;
declare const TypedArray: typeof _TypedArray;
declare const TypedArray_Int32: typeof _TypedArray_Int32;
declare const TypedArray_Float64: typeof _TypedArray_Float64;
declare const Process: typeof _Process;
declare const BindProcess: typeof _BindProcess;
declare const FileSystem: typeof _FileSystem;
export { Pbr };
export { spinalCore };
export { Model };
export { Str };
export { Bool };
export { Val };
export { Lst };
export { Directory };
export { Vec };
export { Path };
export { File };
export { Ptr };
export { Choice };
export { TypedArray };
export { TypedArray_Int32 };
export { TypedArray_Float64 };
export { Process };
export { BindProcess };
export { FileSystem };
